version: "3.9"

services:
  peaceful:
    image: "itzg/minecraft-bedrock-server"
    dns_search: "."
    stdin_open: true
    environment:
      SERVER_NAME: "Unset"
      EULA: "TRUE"
      VERSION: "LATEST"
      GAMEMODE: "survival"
      DIFFICULTY: "peaceful"
      ALLOW_CHEATS: "true"
      DEFAULT_PERMISSION_LEVEL: "member"
      ONLINE_MODE: "false"
      LEVEL_NAME: "Portainer"
      LEVEL_SEED: "1"
      LEVEL_TYPE: "DEFAULT"
      SERVER_PORT: "19132"
    networks:
      - swarm-lan
    deploy:
      replicas: 1
      restart_policy:
        condition: "any"
        max_attempts: 10
        delay: "60s"
      placement:
        constraints:
          - node.hostname == server

networks:
  swarm-lan:
    external: true
